### ISSUE TITLE
If the user is not in the "latest" state, and a new state is added, should we remove the remaining, "unused" states and go from there?

### ISSUE THREAD

**Issue by lsmoura** [TomSaporito/substate#4]
Consider the following state changes scenario

- add 'foo'
- add 'bar'
- add 'fox'
- go back one (current state is 'bar')
- add 'bump'

In the end, our state array will be `['foo', 'bar', 'fox', 'bump']`. Should it be `['foo', 'bar', 'bump']` instead?

**Comment by TomSaporito** [comment]
That's an interesting question.  I thought of this.  And then I realized that the User should be limited in their selection of "State". It should really be the developer's call.  That's why I have a `changeState` method.  I think that should cover most use cases.  I'll definitely consider this though.

**Comment by lsmoura** [comment]
This would implement what I said above: https://github.com/lsmoura/substate/commit/aa53eb6efe067b3b811d2feb2a11dd7ac079b2fe
